name: Security scan for cx-flow Plugin
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Scheduled scan every monday at 8 AM
  schedule:
    - cron: '0 8 * * 1'
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'checkmarx-ltd/cx-flow'
          path: 'cx-flow'
          ref: 'master'
      
      - name: Run Checkmarx scan
        id: scan-cxflow
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v2.3
        continue-on-error: true
        with:
          project: cx-flow-new-scan
          team: ${{ secrets.CHECKMARX_TEAMS }}
          scanners: sca
          bug_tracker: Json
          # Set the environment variables for SCA scan
          sca_api_url: ${{ secrets.SCA_API_URL }}
          sca_app_url: ${{ secrets.SCA_APP_URL }}
          sca_access_control_url: ${{ secrets.SCA_ACCESS_CONTROL_URL }}
          sca_tenant: ${{  secrets.SCA_TENANT }}
          sca_username: ${{ secrets.SCA_USERNAME }}
          sca_password: ${{ secrets.SCA_PASSWORD }}
          #--f is the path to the source code from checkout code step
          params: "--logging.level.com.checkmarx.*=DEBUG --json.data-folder=./scans --sca.enable-sca-resolver=true --f=."

      #verify if the file ./cx.sarif is created    
      - name: Check if scan results exist
        run: |
          ls -l  || echo "Directory  does not exist."
          ls -l /scans || echo "Directory  does not exist."

      - name: upload Sarif file
        uses: actions/upload-artifact@v4
        with:
          name: scan-results-${{ github.run_number }}
          path: ./scans/*.json
          retention-days: 7  
       